# Set Airflow and Python version
ARG AIRFLOW_VERSION=${AIRFLOW_VERSION}
ARG PYTHON_VERSION=${PYTHON_VERSION}

# Airflow image
FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

# Add any providers down here
