server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - multiline:
          firstline: '^(\[|\{)'
          max_wait_time: 3s
      - replace:
          expression: '(\n)'
          replace: '\\n'
      - regex:
          expression: '^\[.*\] {(?P<filename>.*):.*} (?P<level>[A-Z]*) - (?P<message>.*)'
      - json:
          expressions:
            dag_id: dag_id
            task_id: task_id
            level: levelname
            try_number: try_number
            execution_date: execution_date
            message: message
      - replace:
          expression: '(Level None)'
          replace: 'INFO'
          source: level
      - labels:
          dag_id:
          task_id:
          level:
          filename:
          try_number:
          execution_date:
      # Fix multi line if there was no message
      - replace:
          expression: '(\\\\n)'
          replace: "\n"
      # Fix multi line if there was a message
      - replace:
          expression: '(\\\\n)'
          replace: "\n"
          source: message
      - output:
          source: message
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'